#### Similarity Analysis

## Install necessary packages and load libraries
install.packages("FactoMineR")
install.packages("vegan")
install.packages("car")
install.packages("ape")
install.packages("sparcl")
install.packages('ggdendro')
library(FactoMineR)
library(vegan)
library(car)
library(ape)
library(sparcl)
library(ggdendro)

## Set working directory
setwd("~/Documents/R/count")

## Load data for single sample analysis
count<-read.table("final.txt", header = TRUE, row.names =1)

## Subset data for analysis of single samples
count.B1<-subset(count[1:8, ])
count.B13<-subset(count[9: 16, ])
count.B3<-subset(count[17: 24, ])
count.B7<-subset(count[25: 32, ])
count.B6<-subset(count[33: 40, ])
count.B12<-subset(count[41: 48, ])
count.B10<-subset(count[49: 60, ])
count.B9<-subset(count[61: 72, ])
count.B8<-subset(count[73: 80, ])
count.B11<-subset(count[81: 86, ])
count.B5<-subset(count[87: 94, ])
count.B2<-subset(count[95: 102, ])
count.B4<-subset(count[103: 110, ])
count.M1<-subset(count[111: 118, ])
count.M2<-subset(count[119: 130, ])
count.M3<-subset(count[131: 142, ])
count.M4<-subset(count[143: 154, ])
count.M5<-subset(count[155: 166, ])
count.M6<-subset(count[167: 178, ])
count.M7<-subset(count[179: 186, ])
count.M8<-subset(count[187: 194, ])
count.M9<-subset(count[195: 202, ])
count.M10<-subset(count[203: 210, ])
count.M11<-subset(count[211: 218, ])
count.M12<-subset(count[219: 226, ])
count.M13<-subset(count[227: 238, ])
count.M14<-subset(count[239: 246, ])
count.M15<-subset(count[247: 254, ])
count.M16<-subset(count[255: 261, ])
count.M17<-subset(count[262: 269, ])
count.M18<-subset(count[270: 277, ])
count.M19<-subset(count[278: 285, ])
count.M20<-subset(count[286: 297, ])
count.M21<-subset(count[298: 305, ])
count.M22<-subset(count[306: 313, ])
count.M23<-subset(count[314: 321, ])


## Perform similarity analysis using differnet indices (all indices are able to handle unknown and variable sample size)
## Morisita (to be used with integers only)
mor.B1<-vegdist(count.B1, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B13<-vegdist(count.B13, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B3<-vegdist(count.B3, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B7<-vegdist(count.B7, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B6<-vegdist(count.B6, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B12<-vegdist(count.B12, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B10<-vegdist(count.B10, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B9<-vegdist(count.B9, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B8<-vegdist(count.B8, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B11<-vegdist(count.B11, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B5<-vegdist(count.B5, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B2<-vegdist(count.B2, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.B4<-vegdist(count.B4, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)

mor.M1<-vegdist(count.M1, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M2<-vegdist(count.M2, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M3<-vegdist(count.M3, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M4<-vegdist(count.M4, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M5<-vegdist(count.M5, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M6<-vegdist(count.M6, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M7<-vegdist(count.M7, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M8<-vegdist(count.M8, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M9<-vegdist(count.M9, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M10<-vegdist(count.M10, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M11<-vegdist(count.M11, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M12<-vegdist(count.M12, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M13<-vegdist(count.M13, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M14<-vegdist(count.M14, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M15<-vegdist(count.M15, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M16<-vegdist(count.M16, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M17<-vegdist(count.M17, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M18<-vegdist(count.M18, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M19<-vegdist(count.M19, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M20<-vegdist(count.M20, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M21<-vegdist(count.M21, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M22<-vegdist(count.M22, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.M23<-vegdist(count.M23, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)

## Horn-Morisita (can be used with non-integers)
hor.B1<-vegdist(count.B1, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B13<-vegdist(count.B13, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B3<-vegdist(count.B3, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B7<-vegdist(count.B7, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B6<-vegdist(count.B6, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B12<-vegdist(count.B12, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B10<-vegdist(count.B10, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B9<-vegdist(count.B9, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B8<-vegdist(count.B8, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B11<-vegdist(count.B11, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B5<-vegdist(count.B5, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B2<-vegdist(count.B2, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.B4<-vegdist(count.B4, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)

hor.M1<-vegdist(count.M1, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M2<-vegdist(count.M2, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M3<-vegdist(count.M3, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M4<-vegdist(count.M4, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M5<-vegdist(count.M5, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M6<-vegdist(count.M6, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M7<-vegdist(count.M7, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M8<-vegdist(count.M8, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M9<-vegdist(count.M9, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M10<-vegdist(count.M10, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M11<-vegdist(count.M11, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M12<-vegdist(count.M12, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M13<-vegdist(count.M13, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M14<-vegdist(count.M14, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M15<-vegdist(count.M15, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M16<-vegdist(count.M16, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M17<-vegdist(count.M17, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M18<-vegdist(count.M18, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M19<-vegdist(count.M19, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M20<-vegdist(count.M20, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M21<-vegdist(count.M21, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M22<-vegdist(count.M22, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.M23<-vegdist(count.M23, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)

## Chao (takes into account unseen species)
chao.B1<-vegdist(count.B1, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B13<-vegdist(count.B13, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B3<-vegdist(count.B3, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B7<-vegdist(count.B7, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B6<-vegdist(count.B6, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B12<-vegdist(count.B12, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B10<-vegdist(count.B10, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B9<-vegdist(count.B9, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B8<-vegdist(count.B8, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B11<-vegdist(count.B11, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B5<-vegdist(count.B5, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B2<-vegdist(count.B2, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.B4<-vegdist(count.B4, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)

chao.M1<-vegdist(count.M1, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M2<-vegdist(count.M2, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M3<-vegdist(count.M3, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M4<-vegdist(count.M4, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M5<-vegdist(count.M5, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M6<-vegdist(count.M6, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M7<-vegdist(count.M7, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M8<-vegdist(count.M8, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M9<-vegdist(count.M9, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M10<-vegdist(count.M10, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M11<-vegdist(count.M11, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M12<-vegdist(count.M12, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M13<-vegdist(count.M13, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M14<-vegdist(count.M14, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M15<-vegdist(count.M15, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M16<-vegdist(count.M16, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M17<-vegdist(count.M17, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M18<-vegdist(count.M18, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M19<-vegdist(count.M19, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M20<-vegdist(count.M20, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M21<-vegdist(count.M21, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M22<-vegdist(count.M22, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.M23<-vegdist(count.M23, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)

## Create dendrograms for the three analyses per sample
# Morisita
hc.mor.B1<-hclust(dist(mor.B1))
dend.mor.B1<-ggdendrogram(hc.mor.B1, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B1.pdf")
dend.mor.B1
dev.off()
hc.mor.B13<-hclust(dist(mor.B13))
dend.mor.B13<-ggdendrogram(hc.mor.B13, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B13.pdf")
dend.mor.B13
dev.off()
hc.mor.B3<-hclust(dist(mor.B3))
dend.mor.B3<-ggdendrogram(hc.mor.B3, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B3.pdf")
dend.mor.B3
dev.off()
hc.mor.B7<-hclust(dist(mor.B7))
dend.mor.B7<-ggdendrogram(hc.mor.B7, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B7.pdf")
dend.mor.B7
dev.off()
hc.mor.B6<-hclust(dist(mor.B6))
dend.mor.B6<-ggdendrogram(hc.mor.B6, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B6.pdf")
dend.mor.B6
dev.off()
hc.mor.B12<-hclust(dist(mor.B12))
dend.mor.B12<-ggdendrogram(hc.mor.B12, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B12.pdf")
dend.mor.B12
dev.off()
hc.mor.B10<-hclust(dist(mor.B10))
dend.mor.B10<-ggdendrogram(hc.mor.B10, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B10.pdf")
dend.mor.B10
dev.off()
hc.mor.B9<-hclust(dist(mor.B9))
dend.mor.B9<-ggdendrogram(hc.mor.B9, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B9.pdf")
dend.mor.B9
dev.off()
hc.mor.B8<-hclust(dist(mor.B8))
dend.mor.B8<-ggdendrogram(hc.mor.B8, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B8.pdf")
dend.mor.B8
dev.off()
hc.mor.B11<-hclust(dist(mor.B11))
dend.mor.B11<-ggdendrogram(hc.mor.B11, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B11.pdf")
dend.mor.B11
dev.off()
hc.mor.B5<-hclust(dist(mor.B5))
dend.mor.B5<-ggdendrogram(hc.mor.B5, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B5.pdf")
dend.mor.B5
dev.off()
hc.mor.B2<-hclust(dist(mor.B2))
dend.mor.B2<-ggdendrogram(hc.mor.B2, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B2.pdf")
dend.mor.B2
dev.off()
hc.mor.B4<-hclust(dist(mor.B4))
dend.mor.B4<-ggdendrogram(hc.mor.B4, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.B4.pdf")
dend.mor.B4
dev.off()

hc.mor.M1<-hclust(dist(mor.M1))
dend.mor.M1<-ggdendrogram(hc.mor.M1, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M1.pdf")
dend.mor.M1
dev.off()
hc.mor.M2<-hclust(dist(mor.M2))
dend.mor.M2<-ggdendrogram(hc.mor.M2, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M2.pdf")
dend.mor.M2
dev.off()
hc.mor.M3<-hclust(dist(mor.M3))
dend.mor.M3<-ggdendrogram(hc.mor.M3, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M3.pdf")
dend.mor.M3
dev.off()
hc.mor.M4<-hclust(dist(mor.M4))
dend.mor.M4<-ggdendrogram(hc.mor.M4, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
hc.mor.M4
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M4.pdf")
dev.off()
hc.mor.M5<-hclust(dist(mor.M5))
dend.mor.M5<-ggdendrogram(hc.mor.M5, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M5.pdf")
dend.mor.M5
dev.off()
hc.mor.M6<-hclust(dist(mor.M6))
dend.mor.M6<-ggdendrogram(hc.mor.M6, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M6.pdf")
dend.mor.M6
dev.off()
hc.mor.M7<-hclust(dist(mor.M7))
dend.mor.M7<-ggdendrogram(hc.mor.M7, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M7.pdf")
dend.mor.M7
dev.off()
hc.mor.M8<-hclust(dist(mor.M8))
dend.mor.M8<-ggdendrogram(hc.mor.M8, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M8.pdf")
dend.mor.M8
dev.off()
hc.mor.M9<-hclust(dist(mor.M9))
dend.mor.M9<-ggdendrogram(hc.mor.M9, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M9.pdf")
dend.mor.M9
dev.off()
hc.mor.M10<-hclust(dist(mor.M10))
dend.mor.M10<-ggdendrogram(hc.mor.M10, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M10.pdf")
dend.mor.M10
dev.off()
hc.mor.M11<-hclust(dist(mor.M11))
dend.mor.M11<-ggdendrogram(hc.mor.M11, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M11.pdf")
dend.mor.M11
dev.off()
hc.mor.M12<-hclust(dist(mor.M12))
dend.mor.M12<-ggdendrogram(hc.mor.M12, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M12.pdf")
dend.mor.M12
dev.off()
hc.mor.M13<-hclust(dist(mor.M13))
dend.mor.M13<-ggdendrogram(hc.mor.M13, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M13.pdf")
dend.mor.M13
dev.off()
hc.mor.M14<-hclust(dist(mor.M14))
dend.mor.M14<-ggdendrogram(hc.mor.M14, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M14.pdf")
dend.mor.M14
dev.off()
hc.mor.M15<-hclust(dist(mor.M15))
dend.mor.M15<-ggdendrogram(hc.mor.M15, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M15.pdf")
dend.mor.M15
dev.off()
hc.mor.M16<-hclust(dist(mor.M16))
dend.mor.M16<-ggdendrogram(hc.mor.M16, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M16.pdf")
dend.mor.M16
dev.off()
hc.mor.M17<-hclust(dist(mor.M17))
dend.mor.M17<-ggdendrogram(hc.mor.M17, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M17.pdf")
dend.mor.M17
dev.off()
hc.mor.M18<-hclust(dist(mor.M18))
dend.mor.M18<-ggdendrogram(hc.mor.M18, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M18.pdf")
dend.mor.M18
dev.off()
hc.mor.M19<-hclust(dist(mor.M19))
dend.mor.M19<-ggdendrogram(hc.mor.M19, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M19.pdf")
dend.mor.M19
dev.off()
hc.mor.M20<-hclust(dist(mor.M20))
dend.mor.M20<-ggdendrogram(hc.mor.M20, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M20.pdf")
dend.mor.M20
dev.off()
hc.mor.M21<-hclust(dist(mor.M21))
dend.mor.M21<-ggdendrogram(hc.mor.M21, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M21.pdf")
dend.mor.M21
dev.off()
hc.mor.M22<-hclust(dist(mor.M22))
dend.mor.M22<-ggdendrogram(hc.mor.M22, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M22.pdf")
dend.mor.M22
dev.off()
hc.mor.M23<-hclust(dist(mor.M23))
dend.mor.M23<-ggdendrogram(hc.mor.M23, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.M23.pdf")
dend.mor.M23
dev.off()


# Horn-Morisita
hc.hor.B1<-hclust(dist(hor.B1))
dend.hor.B1<-ggdendrogram(hc.hor.B1, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B1.pdf")
dend.hor.B1
dev.off()
hc.hor.B13<-hclust(dist(hor.B13))
dend.hor.B13<-ggdendrogram(hc.hor.B13, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B13.pdf")
dend.hor.B13
dev.off()
hc.hor.B3<-hclust(dist(hor.B3))
dend.hor.B3<-ggdendrogram(hc.hor.B3, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B3.pdf")
dend.hor.B3
dev.off()
hc.hor.B7<-hclust(dist(hor.B7))
dend.hor.B7<-ggdendrogram(hc.hor.B7, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B7.pdf")
dend.hor.B7
dev.off()
hc.hor.B6<-hclust(dist(hor.B6))
dend.hor.B6<-ggdendrogram(hc.hor.B6, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B6.pdf")
dend.hor.B6
dev.off()
hc.hor.B12<-hclust(dist(hor.B12))
dend.hor.B12<-ggdendrogram(hc.hor.B12, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B12.pdf")
dend.hor.B12
dev.off()
hc.hor.B10<-hclust(dist(hor.B10))
dend.hor.B10<-ggdendrogram(hc.hor.B10, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B10.pdf")
dend.hor.B10
dev.off()
hc.hor.B9<-hclust(dist(hor.B9))
dend.hor.B9<-ggdendrogram(hc.hor.B9, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B9.pdf")
dend.hor.B9
dev.off()
hc.hor.B8<-hclust(dist(hor.B8))
dend.hor.B8<-ggdendrogram(hc.hor.B8, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B8.pdf")
dend.hor.B8
dev.off()
hc.hor.B11<-hclust(dist(hor.B11))
dend.hor.B11<-ggdendrogram(hc.hor.B11, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B11.pdf")
dend.hor.B11
dev.off()
hc.hor.B5<-hclust(dist(hor.B5))
dend.hor.B5<-ggdendrogram(hc.hor.B5, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B5.pdf")
dend.hor.B5
dev.off()
hc.hor.B2<-hclust(dist(hor.B2))
dend.hor.B2<-ggdendrogram(hc.hor.B2, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B2.pdf")
dend.hor.B2
dev.off()
hc.hor.B4<-hclust(dist(hor.B4))
dend.hor.B4<-ggdendrogram(hc.hor.B4, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.B4.pdf")
dend.hor.B4
dev.off()

hc.hor.M1<-hclust(dist(hor.M1))
dend.hor.M1<-ggdendrogram(hc.hor.M1, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M1.pdf")
dend.hor.M1
dev.off()
hc.hor.M2<-hclust(dist(hor.M2))
dend.hor.M2<-ggdendrogram(hc.hor.M2, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M2.pdf")
dend.hor.M2
dev.off()
hc.hor.M3<-hclust(dist(hor.M3))
dend.hor.M3<-ggdendrogram(hc.hor.M3, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M3.pdf")
dend.hor.M3
dev.off()
hc.hor.M4<-hclust(dist(hor.M4))
dend.hor.M4<-ggdendrogram(hc.hor.M4, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
hc.hor.M4
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M4.pdf")
dev.off()
hc.hor.M5<-hclust(dist(hor.M5))
dend.hor.M5<-ggdendrogram(hc.hor.M5, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M5.pdf")
dend.hor.M5
dev.off()
hc.hor.M6<-hclust(dist(hor.M6))
dend.hor.M6<-ggdendrogram(hc.hor.M6, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M6.pdf")
dend.hor.M6
dev.off()
hc.hor.M7<-hclust(dist(hor.M7))
dend.hor.M7<-ggdendrogram(hc.hor.M7, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M7.pdf")
dend.hor.M7
dev.off()
hc.hor.M8<-hclust(dist(hor.M8))
dend.hor.M8<-ggdendrogram(hc.hor.M8, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M8.pdf")
dend.hor.M8
dev.off()
hc.hor.M9<-hclust(dist(hor.M9))
dend.hor.M9<-ggdendrogram(hc.hor.M9, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M9.pdf")
dend.hor.M9
dev.off()
hc.hor.M10<-hclust(dist(hor.M10))
dend.hor.M10<-ggdendrogram(hc.hor.M10, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M10.pdf")
dend.hor.M10
dev.off()
hc.hor.M11<-hclust(dist(hor.M11))
dend.hor.M11<-ggdendrogram(hc.hor.M11, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M11.pdf")
dend.hor.M11
dev.off()
hc.hor.M12<-hclust(dist(hor.M12))
dend.hor.M12<-ggdendrogram(hc.hor.M12, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M12.pdf")
dend.hor.M12
dev.off()
hc.hor.M13<-hclust(dist(hor.M13))
dend.hor.M13<-ggdendrogram(hc.hor.M13, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M13.pdf")
dend.hor.M13
dev.off()
hc.hor.M14<-hclust(dist(hor.M14))
dend.hor.M14<-ggdendrogram(hc.hor.M14, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M14.pdf")
dend.hor.M14
dev.off()
hc.hor.M15<-hclust(dist(hor.M15))
dend.hor.M15<-ggdendrogram(hc.hor.M15, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M15.pdf")
dend.hor.M15
dev.off()
hc.hor.M16<-hclust(dist(hor.M16))
dend.hor.M16<-ggdendrogram(hc.hor.M16, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M16.pdf")
dend.hor.M16
dev.off()
hc.hor.M17<-hclust(dist(hor.M17))
dend.hor.M17<-ggdendrogram(hc.hor.M17, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M17.pdf")
dend.hor.M17
dev.off()
hc.hor.M18<-hclust(dist(hor.M18))
dend.hor.M18<-ggdendrogram(hc.hor.M18, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M18.pdf")
dend.hor.M18
dev.off()
hc.hor.M19<-hclust(dist(hor.M19))
dend.hor.M19<-ggdendrogram(hc.hor.M19, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M19.pdf")
dend.hor.M19
dev.off()
hc.hor.M20<-hclust(dist(hor.M20))
dend.hor.M20<-ggdendrogram(hc.hor.M20, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M20.pdf")
dend.hor.M20
dev.off()
hc.hor.M21<-hclust(dist(hor.M21))
dend.hor.M21<-ggdendrogram(hc.hor.M21, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M21.pdf")
dend.hor.M21
dev.off()
hc.hor.M22<-hclust(dist(hor.M22))
dend.hor.M22<-ggdendrogram(hc.hor.M22, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M22.pdf")
dend.hor.M22
dev.off()
hc.hor.M23<-hclust(dist(hor.M23))
dend.hor.M23<-ggdendrogram(hc.hor.M23, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.M23.pdf")
dend.hor.M23
dev.off()

# Chao
hc.chao.B1<-hclust(dist(chao.B1))
dend.chao.B1<-ggdendrogram(hc.chao.B1, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B1.pdf")
dend.chao.B1
dev.off()
hc.chao.B13<-hclust(dist(chao.B13))
dend.chao.B13<-ggdendrogram(hc.chao.B13, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B13.pdf")
dend.chao.B13
dev.off()
hc.chao.B3<-hclust(dist(chao.B3))
dend.chao.B3<-ggdendrogram(hc.chao.B3, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B3.pdf")
dend.chao.B3
dev.off()
hc.chao.B7<-hclust(dist(chao.B7))
dend.chao.B7<-ggdendrogram(hc.chao.B7, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B7.pdf")
dend.chao.B7
dev.off()
hc.chao.B6<-hclust(dist(chao.B6))
dend.chao.B6<-ggdendrogram(hc.chao.B6, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B6.pdf")
dend.chao.B6
dev.off()
hc.chao.B12<-hclust(dist(chao.B12))
dend.chao.B12<-ggdendrogram(hc.chao.B12, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B12.pdf")
dend.chao.B12
dev.off()
hc.chao.B10<-hclust(dist(chao.B10))
dend.chao.B10<-ggdendrogram(hc.chao.B10, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B10.pdf")
dend.chao.B10
dev.off()
hc.chao.B9<-hclust(dist(chao.B9))
dend.chao.B9<-ggdendrogram(hc.chao.B9, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B9.pdf")
dend.chao.B9
dev.off()
hc.chao.B8<-hclust(dist(chao.B8))
dend.chao.B8<-ggdendrogram(hc.chao.B8, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B8.pdf")
dend.chao.B8
dev.off()
hc.chao.B11<-hclust(dist(chao.B11))
dend.chao.B11<-ggdendrogram(hc.chao.B11, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B11.pdf")
dend.chao.B11
dev.off()
hc.chao.B5<-hclust(dist(chao.B5))
dend.chao.B5<-ggdendrogram(hc.chao.B5, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B5.pdf")
dend.chao.B5
dev.off()
hc.chao.B2<-hclust(dist(chao.B2))
dend.chao.B2<-ggdendrogram(hc.chao.B2, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B2.pdf")
dend.chao.B2
dev.off()
hc.chao.B4<-hclust(dist(chao.B4))
dend.chao.B4<-ggdendrogram(hc.chao.B4, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.B4.pdf")
dend.chao.B4
dev.off()

hc.chao.M1<-hclust(dist(chao.M1))
dend.chao.M1<-ggdendrogram(hc.chao.M1, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M1.pdf")
dend.chao.M1
dev.off()
hc.chao.M2<-hclust(dist(chao.M2))
dend.chao.M2<-ggdendrogram(hc.chao.M2, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M2.pdf")
dend.chao.M2
dev.off()
hc.chao.M3<-hclust(dist(chao.M3))
dend.chao.M3<-ggdendrogram(hc.chao.M3, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M3.pdf")
dend.chao.M3
dev.off()
hc.chao.M4<-hclust(dist(chao.M4))
dend.chao.M4<-ggdendrogram(hc.chao.M4, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
hc.chao.M4
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M4.pdf")
dev.off()
hc.chao.M5<-hclust(dist(chao.M5))
dend.chao.M5<-ggdendrogram(hc.chao.M5, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M5.pdf")
dend.chao.M5
dev.off()
hc.chao.M6<-hclust(dist(chao.M6))
dend.chao.M6<-ggdendrogram(hc.chao.M6, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M6.pdf")
dend.chao.M6
dev.off()
hc.chao.M7<-hclust(dist(chao.M7))
dend.chao.M7<-ggdendrogram(hc.chao.M7, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M7.pdf")
dend.chao.M7
dev.off()
hc.chao.M8<-hclust(dist(chao.M8))
dend.chao.M8<-ggdendrogram(hc.chao.M8, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M8.pdf")
dend.chao.M8
dev.off()
hc.chao.M9<-hclust(dist(chao.M9))
dend.chao.M9<-ggdendrogram(hc.chao.M9, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M9.pdf")
dend.chao.M9
dev.off()
hc.chao.M10<-hclust(dist(chao.M10))
dend.chao.M10<-ggdendrogram(hc.chao.M10, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M10.pdf")
dend.chao.M10
dev.off()
hc.chao.M11<-hclust(dist(chao.M11))
dend.chao.M11<-ggdendrogram(hc.chao.M11, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M11.pdf")
dend.chao.M11
dev.off()
hc.chao.M12<-hclust(dist(chao.M12))
dend.chao.M12<-ggdendrogram(hc.chao.M12, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M12.pdf")
dend.chao.M12
dev.off()
hc.chao.M13<-hclust(dist(chao.M13))
dend.chao.M13<-ggdendrogram(hc.chao.M13, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M13.pdf")
dend.chao.M13
dev.off()
hc.chao.M14<-hclust(dist(chao.M14))
dend.chao.M14<-ggdendrogram(hc.chao.M14, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M14.pdf")
dend.chao.M14
dev.off()
hc.chao.M15<-hclust(dist(chao.M15))
dend.chao.M15<-ggdendrogram(hc.chao.M15, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M15.pdf")
dend.chao.M15
dev.off()
hc.chao.M16<-hclust(dist(chao.M16))
dend.chao.M16<-ggdendrogram(hc.chao.M16, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M16.pdf")
dend.chao.M16
dev.off()
hc.chao.M17<-hclust(dist(chao.M17))
dend.chao.M17<-ggdendrogram(hc.chao.M17, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M17.pdf")
dend.chao.M17
dev.off()
hc.chao.M18<-hclust(dist(chao.M18))
dend.chao.M18<-ggdendrogram(hc.chao.M18, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M18.pdf")
dend.chao.M18
dev.off()
hc.chao.M19<-hclust(dist(chao.M19))
dend.chao.M19<-ggdendrogram(hc.chao.M19, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M19.pdf")
dend.chao.M19
dev.off()
hc.chao.M20<-hclust(dist(chao.M20))
dend.chao.M20<-ggdendrogram(hc.chao.M20, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M20.pdf")
dend.chao.M20
dev.off()
hc.chao.M21<-hclust(dist(chao.M21))
dend.chao.M21<-ggdendrogram(hc.chao.M21, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M21.pdf")
dend.chao.M21
dev.off()
hc.chao.M22<-hclust(dist(chao.M22))
dend.chao.M22<-ggdendrogram(hc.chao.M22, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M22.pdf")
dend.chao.M22
dev.off()
hc.chao.M23<-hclust(dist(chao.M23))
dend.chao.M23<-ggdendrogram(hc.chao.M23, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.M23.pdf")
dend.chao.M23
dev.off()

## Load data for white vs fireplace analysis (per site)
typ<-read.table("stats.txt", header = TRUE, row.names =1)

## Subset data for analysis of single samples
typ.BH<-subset(typ[1:56, ])
typ.MH<-subset(typ[57: 88, ])
typ.BW<-subset(typ[89: 142, ])
typ.MW<-subset(typ[143: 321, ])

## Perform similarity analysis using differnet indices (all indices are able to handle unknown and variable sample size)
## Morisita (to be used with integers only)
mor.BH<-vegdist(typ.BH, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.MH<-vegdist(typ.MH, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.BW<-vegdist(typ.BW, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
mor.MW<-vegdist(typ.MW, method = "morisita", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)

## Horn-Morisita (can be used with non-integers)
hor.BH<-vegdist(typ.BH, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.MH<-vegdist(typ.MH, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.BW<-vegdist(typ.BW, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
hor.MW<-vegdist(typ.MW, method = "horn", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)

## Chao (takes into account unseen species)
chao.BH<-vegdist(typ.BH, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.MH<-vegdist(typ.MH, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.BW<-vegdist(typ.BW, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
chao.MW<-vegdist(typ.MW, method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)

## Create dendrograms for the three analyses per sample
# Morisita
hc.mor.BH<-hclust(dist(mor.BH))
dend.mor.BH<-ggdendrogram(hc.mor.BH, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.BH.pdf")
dend.mor.BH
dev.off()
hc.mor.MH<-hclust(dist(mor.MH))
dend.mor.MH<-ggdendrogram(hc.mor.MH, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.MH.pdf")
dend.mor.MH
dev.off()
hc.mor.BW<-hclust(dist(mor.BW))
dend.mor.BW<-ggdendrogram(hc.mor.BW, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.BW.pdf")
dend.mor.BW
dev.off()
hc.mor.MW<-hclust(dist(mor.MW))
dend.mor.MW<-ggdendrogram(hc.mor.MW, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Morisita/dend.mor.MW.pdf")
dend.mor.MW
dev.off()

# Horn-Morisita
hc.hor.BH<-hclust(dist(hor.BH))
dend.hor.BH<-ggdendrogram(hc.hor.BH, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.BH.pdf")
dend.hor.BH
dev.off()
hc.hor.MH<-hclust(dist(hor.MH))
dend.hor.MH<-ggdendrogram(hc.hor.MH, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.MH.pdf")
dend.hor.MH
dev.off()
hc.hor.BW<-hclust(dist(hor.BW))
dend.hor.BW<-ggdendrogram(hc.hor.BW, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.BW.pdf")
dend.hor.BW
dev.off()
hc.hor.MW<-hclust(dist(hor.MW))
dend.hor.MW<-ggdendrogram(hc.hor.MW, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Horn/dend.hor.MW.pdf")
dend.hor.MW
dev.off()

# Chao
hc.chao.BH<-hclust(dist(chao.BH))
dend.chao.BH<-ggdendrogram(hc.chao.BH, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.BH.pdf")
dend.chao.BH
dev.off()
hc.chao.MH<-hclust(dist(chao.MH))
dend.chao.MH<-ggdendrogram(hc.chao.MH, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.MH.pdf")
dend.chao.MH
dev.off()
hc.chao.BW<-hclust(dist(chao.BW))
dend.chao.BW<-ggdendrogram(hc.chao.BW, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.BW.pdf")
dend.chao.BW
dev.off()
hc.chao.MW<-hclust(dist(chao.MW))
dend.chao.MW<-ggdendrogram(hc.chao.MW, rotate = TRUE, size = 4, theme_dendro = FALSE, color = "tomato")
pdf("~/Documents/R/count/Graphs/Chao/dend.chao.MW.pdf")
dend.chao.MW
dev.off()
