#### Similarity Analysis

## Install necessary packages and load libraries
install.packages("FactoMineR")
install.packages("vegan")
install.packages("car")
install.packages("ape")
install.packages("sparcl")
install.packages('ggdendro')
library(FactoMineR)
library(vegan)
library(car)
library(ape)
library(sparcl)
library(ggdendro)
library(digest)

# Set working directory
setwd("F:/R")

## Chao Control 1 (LTS+VHV)
Control1<-read.table("ChaoControl1.txt", header=TRUE, row.names=14)
chao<-vegdist(Control1[ ,1:13], method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
summary(chao)
quantile(chao, c(.75, .95, .98))
par(mar=c(5,5,3,1.5))
par(oma=c(2,0,0,0))
pdf("F:/R/Graphs/Chao_Control1.pdf")
hc<-hclust(dist(chao))
dend<-as.dendrogram(hc)
plot(dend, nodePar = list(col=1), edgePar = list(lty = 1:2, col = 2:1), edge.root = TRUE)
dev.off()

## Chao Control 2 (SKP)
Control2<-read.table("ChaoControl2.txt", header=TRUE, row.names=14)
chao<-vegdist(Control2[ ,1:13], method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE)
summary(chao)
quantile(chao, c(.75, .95, .98))
par(mar=c(5,5,3,1.5))
par(oma=c(2,0,0,0))
pdf("F:/R/Graphs/Chao_Control2.pdf")
hc<-hclust(dist(chao))
dend<-as.dendrogram(hc)
plot(dend, nodePar = list(col=1), edgePar = list(lty = 1:2, col = 2:1), edge.root = TRUE)
dev.off()

## Chao SKP
SKP<-read.table("ChaoSKP.txt", header=TRUE, row.names=24)
chao<-vegdist(SKP[ ,1:23], method = "chao", binary = FALSE, diag = FALSE, upper = FALSE, na.rm = FALSE, names = 24)
summary(chao)
quantile(chao, c(.75, .95, .98))
par(mar=c(5,5,3,1.5))
par(oma=c(2,0,0,0))
pdf("F:/R/Graphs/Chao_SKP.pdf")
hc<-hclust(dist(chao))
dend<-as.dendrogram(hc)
plot(dend, nodePar = list(col=1), edgePar = list(lty = 1:2, col = 2:1), edge.root = TRUE)
dev.off()
